-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 09:55:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8mb3 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `passwordconfirm` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `mobile` VARCHAR(45) NULL DEFAULT NULL,
  `registered_at` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`myorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`myorder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `grand_total` DECIMAL(10,0) NULL DEFAULT NULL,
  `dateoforder` DATE NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `myorder_ibfk_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `myorder_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `database`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `image` VARCHAR(2000) NULL DEFAULT NULL,
  `manufacturer_id` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `usersvote` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  INDEX `manufacturer_id` (`manufacturer_id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `database`.`supplier` (`id`),
  CONSTRAINT `product_ibfk_4`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `database`.`manufacturer` (`id`),
  CONSTRAINT `product_ibfk_5`
    FOREIGN KEY (`category_id`)
    REFERENCES `database`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`orderproductmap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`orderproductmap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `orderid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `orderproductmap_ibfk_2_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `orderproductmap_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `database`.`product` (`id`),
  CONSTRAINT `orderproductmap_ibfk_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `database`.`myorder` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `users_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `content` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id` (`users_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `review_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `database`.`user` (`id`),
  CONSTRAINT `review_ibfk_3`
    FOREIGN KEY (`product_id`)
    REFERENCES `database`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`user_roles` (
  `user_id` INT NULL DEFAULT NULL,
  `roles_id` INT NULL DEFAULT NULL,
  INDEX `user_roles_ibfk_1_idx` (`user_id` ASC) VISIBLE,
  INDEX `user_roles_ibfk_2_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `user_roles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `database`.`user` (`id`),
  CONSTRAINT `user_roles_ibfk_2`
    FOREIGN KEY (`roles_id`)
    REFERENCES `database`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
